### ISSUE TITLE
not working with Vivaldi because of missing profile-sync

### ISSUE THREAD

**Issue by phpmoli** [xisberto/phonetodesktop-chrome#7]
Dear Humberto,

Recently I've migrated from Chrome to [Vivaldi](https://en.wikipedia.org/wiki/Vivaldi_%28web_browser%29), and  along my data, i've moved my good old extensions too. From all my extensions, the only one not working is the P2D. The reason could be: Vivaldi does not implement Chrome profile-sign in and synchronization, they are planning to use their own service later for this, maybe they will do this using the same api calls and everything like google, only with changed uri or such, so everything will work transparently. Anyway, until then P2D is not working, pressing the button shows the loading animation and opens a new tab with the uri `vivaldi://chrome-signin/?access_point=6&reason=0` which shows a standard google login page, like:

> Sign in to Chrome
> Sign in to get your bookmarks, history, and settings on all your devices.
> Choose what to sync

but submitting a form clears the page white and nothing happens, even by the developer tools/networking, no requests made. Oh, and I am logged in to my google account in the browser.

Is there an other way, like making an oauth request to get the permission? Or must this be made using chrome-sync?

Thank you!

**Comment by humbertofraga** [comment]
At the moment, the Chrome extension supports only Chrome. I will be studying the use of oauth requests to make the extension more browser-independent as this kind of extensions will become universal between various browsers in the future.

**Comment by phpmoli** [comment]
Dear @xisberto , never mind, i stopped using Vivaldi as it was constantly freezing during full screen video playback, and even locked up my Debian KDE multiple times to the point i had to do a hard reset, and see data loss on my ssd during fsck on bootup.. so i will never use it again, i went back to Chrome which didnt even freeze for years on the same setup with the same extensions.
